/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.informatica.disseny.vista;

import edu.ub.informatica.disseny.model.Dades;
import edu.ub.informatica.disseny.totseries.TotSeriesDataManager;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author abergaye8.alumnes
 */
public class TotSeries extends javax.swing.JFrame {
    private static TotSeries instance = null;
    private Dades dades;
    private TotSeriesDataManager cont;
    private ArrayList<String> opt;
    private int place;
    protected int serie;
    protected int temporada;
    protected int episodi;
    private int last=-1;
    /**
     * Creates new form TotSeries2
     */
    private TotSeries() {
        place=0;
        serie=-1;
        temporada=-1;
        episodi=-1;
        cont=TotSeriesDataManager.getInstance();
        opt=new ArrayList<>();
        opt.add("Back");
        opt.add("Reproduir");
        opt.add("Valorar");
        this.getContentPane().setBackground(Color.BLACK);
        initComponents();
        Login.setEnabled(true);
        Register.setEnabled(true);
        DefaultListModel temp = new DefaultListModel();
        for(String s : cont.mostratCataleg()){
           temp.addElement(s);
        }
        cataleg.setModel(temp);
    }
    
    public static TotSeries getInstance(){
        if(instance==null){
            instance=new TotSeries();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        cataleg = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(934, 617));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TotSeries");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cataleg");

        jList1.setBackground(new java.awt.Color(55, 55, 55));
        jList1.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setViewportView(jList1);

        cataleg.setBackground(new java.awt.Color(55, 55, 55));
        cataleg.setForeground(new java.awt.Color(238, 238, 238));
        cataleg.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                catalegComponentAdded(evt);
            }
        });
        cataleg.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                catalegValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(cataleg);

        jList3.setBackground(new java.awt.Color(55, 55, 55));
        jList3.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setViewportView(jList3);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Més vists");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Millor Valorats");

        Register.setBackground(new java.awt.Color(55, 55, 55));
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(55, 55, 55));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Login)
                        .addGap(18, 18, 18)
                        .addComponent(Register))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register)
                    .addComponent(Login)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        new RegisterDialog(this,true).setVisible(true);
    }//GEN-LAST:event_RegisterActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        new LoginDialog(this,true).setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    public void turnOffLogin(){
        Login.setEnabled(false);
    }
    
    private void catalegComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_catalegComponentAdded
        
    }//GEN-LAST:event_catalegComponentAdded

    private void catalegValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_catalegValueChanged
        // TODO add your handling code here:
        int pos=cataleg.getSelectedIndex();
        if(pos!=-1 && last!=pos){
            OUTER:
            switch (place) {
                case 0:
                    serie=pos;
                    this.actualitzaLlista(cont.mostratTemporades(serie));
                    place=1;
                    break;
                case 1:
                    if(pos==0){
                        this.actualitzaLlista(cont.mostratCataleg());
                        place=0;
                    }else{
                        temporada=pos-1;
                        this.actualitzaLlista(cont.mostratEpisodis(serie,temporada));
                        place=2;
                    }   break;
                case 2:
                    if(pos==0){
                        this.actualitzaLlista(cont.mostratTemporades(serie));
                        place=1;
                    }else{
                        episodi=pos-1;
                        place=3;
                        this.actualitzaLlista(opt);
                    }   break;
                case 3:
                    switch (pos) {
                        case 0:
                            this.actualitzaLlista(cont.mostratEpisodis(serie,temporada));
                            place=2;
                            break;
                        case 1:
                            if(cont.userIsLoged()){
                                cont.reproduirEpisodi(serie, temporada, episodi);
                            }
                            break;
                        case 2:
                            if(cont.userIsLoged() && cont.getEstat(serie, temporada, episodi).equals("VIST")){
                                new ValorarDialog(this,true).setVisible(true);
                            }
                            break;
                    }
            }
        }
        last=pos;
    }//GEN-LAST:event_catalegValueChanged

    public void actualitzaLlista(ArrayList<String> llista){
        DefaultListModel temp = new DefaultListModel();
        for(String s : llista){
           temp.addElement(s);
        }
        cataleg.setModel(temp);
    }
    
    public void changeLogin(String id){
        this.Login.setText(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton Register;
    private javax.swing.JList<String> cataleg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
